export const bloodGroups: string[] = [
  "A",
  "A+",
  "A-",
  "B",
  "B+",
  "B-",
  "AB",
  "AB+",
  "AB-",
  "O",
  "O+",
  "O-"
];

export const enDivisions: string[] = [
  "Dhaka",
  "Chattogram",
  "Rajshahi",
  "Khulna",
  "Barishal",
  "Sylhet",
  "Rangpur",
  "Mymensingh",
];

export const bnDivisions = [
  "বরিশাল",
  "চট্টগ্রাম",
  "ঢাকা",
  "খুলনা",
  "ময়মনসিংহ",
  "রাজশাহী",
  "রংপুর",
  "সিলেট"
];

export const enDistricts = {
  Dhaka: [
    "Dhaka",
    "Gazipur",
    "Kishoreganj",
    "Manikganj",
    "Munshiganj",
    "Narayanganj",
    "Narsingdi",
    "Tangail",
    "Faridpur",
    "Gopalganj",
    "Madaripur",
    "Rajbari",
    "Shariatpur",
  ],
  Chattogram: [
    "Chattogram",
    "Bandarban",
    "Brahmanbaria",
    "Chandpur",
    "Cox's Bazar",
    "Cumilla",
    "Feni",
    "Khagrachari",
    "Lakshmipur",
    "Noakhali",
    "Rangamati",
  ],
  Rajshahi: [
    "Rajshahi",
    "Bogura",
    "Chapainawabganj",
    "Joypurhat",
    "Naogaon",
    "Natore",
    "Pabna",
    "Sirajganj",
  ],
  Khulna: [
    "Khulna",
    "Bagerhat",
    "Chuadanga",
    "Jashore",
    "Jhenaidah",
    "Kushtia",
    "Magura",
    "Meherpur",
    "Narail",
    "Satkhira",
  ],
  Barishal: [
    "Barishal",
    "Barguna",
    "Bhola",
    "Jhalokati",
    "Patuakhali",
    "Pirojpur",
  ],
  Sylhet: [
    "Sylhet",
    "Habiganj",
    "Moulvibazar",
    "Sunamganj",
  ],
  Rangpur: [
    "Rangpur",
    "Dinajpur",
    "Gaibandha",
    "Kurigram",
    "Lalmonirhat",
    "Nilphamari",
    "Panchagarh",
    "Thakurgaon",
  ],
  Mymensingh: [
    "Mymensingh",
    "Jamalpur",
    "Netrokona",
    "Sherpur",
  ]
};

export const bnDistricts = {
  Dhaka: [
    "ঢাকা",
    "গাজীপুর",
    "কিশোরগঞ্জ",
    "মানিকগঞ্জ",
    "মুন্সীগঞ্জ",
    "নারায়ণগঞ্জ",
    "নরসিংদী",
    "টাঙ্গাইল",
    "ফরিদপুর",
    "গোপালগঞ্জ",
    "মাদারীপুর",
    "রাজবাড়ি",
    "শরীয়তপুর",
  ],
  Chattogram: [
    "চট্টগ্রাম",
    "বান্দরবান",
    "ব্রাহ্মণবাড়িয়া",
    "চাঁদপুর",
    "কক্সবাজার",
    "কুমিল্লা",
    "ফেনী",
    "খাগড়াছড়ি",
    "লক্ষ্মীপুর",
    "নোয়াখালী",
    "রাঙ্গামাটি",
  ],
  Rajshahi: [
    "রাজশাহী",
    "বগুড়া",
    "চাঁপাইনবাবগঞ্জ",
    "জয়পুরহাট",
    "নওগাঁ",
    "নাটোর",
    "পাবনা",
    "সিরাজগঞ্জ",
  ],
  Khulna: [
    "খুলনা",
    "বাগেরহাট",
    "চুয়াডাঙ্গা",
    "যশোর",
    "ঝিনাইদহ",
    "কুষ্টিয়া",
    "মাগুরা",
    "মেহেরপুর",
    "নড়াইল",
    "সাতক্ষীরা",
  ],
  Barishal: [
    "বরিশাল",
    "বরগুনা",
    "ভোলা",
    "ঝালকাঠি",
    "পটুয়াখালী",
    "পিরোজপুর",
  ],
  Sylhet: [
    "সিলেট",
    "হবিগঞ্জ",
    "মৌলভীবাজার",
    "সুনামগঞ্জ",
  ],
  Rangpur: [
    "রংপুর",
    "দিনাজপুর",
    "গাইবান্ধা",
    "কুড়িগ্রাম",
    "লালমনিরহাট",
    "নীলফামারী",
    "পঞ্চগড়",
    "ঠাকুরগাঁও",
  ],
  Mymensingh: [
    "ময়মনসিংহ",
    "জামালপুর",
    "নেত্রকোনা",
    "শেরপুর",
  ]
};

export const bnWards = ["০১", "০২", "০৩", "০৪", "০৫", "০৬", "০৭", "০৮", "০৯", "১০", "১১", "১২", "১৩", "১৪", "১৫", "১৬", "১৭", "১৮", "১৯", "২০", "২১", "২২", "২৩", "২৪", "২৫", "২৬", "২৭", "২৮", "২৯", "৩০", "৩১", "৩২", "৩৩", "৩৪", "৩৫", "৩৬", "৩৭", "৩৮", "৩৯", "৪০", "৪১", "৪২", "৪৩", "৪৪", "৪৫", "৪৬", "৪৭", "৪৮", "৪৯", "৫০"];

export const enWards = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50"];
